[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
parallel = 1
solc_version = "0.8.24"
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
rpc_url="https://unichain-sepolia.g.alchemy.com/v2/YOUR_KEY"
[profile.env]
UNI_SEPOLIA_RPC_URL="https://unichain-sepolia.g.alchemy.com/v2/YOUR_KEY"
